# -*- coding: utf-8 -*-
"""number_checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kyad4q9zGiCyLAg__C5N8QpJ8mv1oRhS

number_checker.py
"""

for number in range(1, 21):
    if number % 2 == 0:
       print(f"{number} is Even")
    else:
        print(f"{number} is Odd")

form google.colab import files
files.download('number_checker.py')